runtime: python37

automatic_scaling:
  target_cpu_utilization: 0.95
  min_instances: 0
  max_instances: 100
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50
